from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage

from pydantic import BaseModel, Field

import base64
from pathlib import Path


class Animal(BaseModel):
    species: str = Field(description="The species of the animal")
    breed: str = Field(description="The breed of the animal")
    features: list[str] = Field(description="List of features used in classification")


class Score(BaseModel):
    score: int = Field(description="The score of the result")


SYSTEM = SystemMessage(
    "You are an expert animal recognition AI. Your task is to analyze images and accurately identify the species (e.g., dog, cat, bird) and, when possible, the specific breed (e.g., Golden Retriever, Siamese, Persian). If the breed is unclear, provide the most likely options or state that the breed is unknown. Be precise, use common breed names, and note any distinctive physical features that support your classification."  # generated by chatgpt
)


def main():
    model = ChatOpenAI(
        model_name="gemma3:4b-it-qat",
        temperature=0,
        openai_api_base="http://localhost:11434/v1",
        openai_api_key="dummy",
    ).with_structured_output(Animal)

    judge = ChatOpenAI(
        model_name="openai/gpt-4.1",
        temperature=0,
    ).with_structured_output(Score)

    result = model.invoke(
        [
            SYSTEM,
            HumanMessage(
                content=[
                    {
                        "type": "text",
                        "text": "Describe the breed and species of the animal in this image, return as JSON",
                    },
                    {
                        "type": "image",
                        "source_type": "base64",
                        "data": base64.b64encode(
                            Path("/tmp/cat.jpg").read_bytes()
                        ).decode(),
                        "mime_type": "image/jpeg",
                    },
                ]
            ),
        ]
    )

    print(result)

    print(
        judge.invoke(
            [
                HumanMessage(
                    content=[
                        {
                            "type": "text",
                            "text": "Judge if the description matches the image, on a scale of 0 to 100, output in JSON",
                        },
                        {
                            "type": "text",
                            "text": result.model_dump_json(),
                        },
                        {
                            "type": "image",
                            "source_type": "base64",
                            "data": base64.b64encode(
                                Path("/tmp/cat.jpg").read_bytes()
                            ).decode(),
                            "mime_type": "image/jpeg",
                        },
                    ]
                ),
            ]
        )
    )


if __name__ == "__main__":
    main()
