from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field


class Animal(BaseModel):
    species: str = Field(description="The species of the animal")
    breed: str = Field(description="The breed of the animal")
    features: list[str] = Field(description="List of features used in classification")


SYSTEM = SystemMessage(
    "You are an expert animal recognition AI. Your task is to analyze images and accurately identify the species (e.g., dog, cat, bird) and, when possible, the specific breed (e.g., Golden Retriever, Siamese, Persian). If the breed is unclear, provide the most likely options or state that the breed is unknown. Be precise, use common breed names, and note any distinctive physical features that support your classification."  # generated by chatgpt
)


def main():
    model = ChatOpenAI(
        model_name="openai/gpt-4.1",
    ).with_structured_output(Animal)

    print(
        model.invoke(
            [
                SYSTEM,
                HumanMessage(
                    content=[
                        {
                            "type": "text",
                            "text": "Describe the breed and species of the animal in this image",
                        },
                        {
                            "type": "image",
                            "source_type": "url",
                            "url": "https://cataas.com/cat",
                        },
                    ]
                ),
            ]
        )
    )


if __name__ == "__main__":
    main()
